<?php

namespace AppBundle\Entity;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends \Doctrine\ORM\EntityRepository {
    private $shop;
    public function saveItem($data) {
        $em = $this->getEntityManager();
        $em->persist(
            $this->applyDataToAnItem($this->getItemByImportInfo($data), $data)
        );
        $em->flush();
    }
    
    public function setShop($shop){
        $this->shop = $shop;
        return $this;
    }

    private function getItemByImportInfo($data) {
        $item = $this->findOneBy(
                [
                    'shopId' => $data['shopId'],
                    'orderId' => $data['orderId']]);

        if (empty($item)) {
            $item = new Order();
        }
        return $item;
    }

    private function applyDataToAnItem($item, $data) {
        $date = new \DateTime();
        $date->setTimestamp($data['createdAt']);
        return $item->setImportShopId($data['importShopId'])
                    ->setOrderId($data['orderId'])
                    ->setShopId($this->shop)
                    ->setState($data['state'])
                    ->setOrderPayment($data['orderPayment'])
                    ->setCurrency($data['currency'])
                    ->setCreatedAt($date);
        
    }

}
