<?php

namespace AppBundle\Entity;

/**
 * ShopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopRepository extends \Doctrine\ORM\EntityRepository
{
    private $timeDelayBetweenImports = '-10 min';
            
    /**
     * @return type
     */
    public function getNextShopToParse(){
        $query = $this->createQueryBuilder('s')
            ->where('s.lastImportTime < :now')
            ->setParameter('now', new \DateTime($this->timeDelayBetweenImports))
            ->setMaxResults(1)
            ->getQuery();
       return $query->getOneOrNullResult();
    }
    
    public function updateLastImportTime(Shop $shop){
        $em = $this->getEntityManager();
        $shop->setLastImportTime(new \DateTime());
        $em->flush();
        return $this;
    }
}
